version: '3.9'
services:
  # Serviço do Zabbix Server (agora com MySQL)
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - ./zbx_alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
    restart: unless-stopped
    networks:
      - zabbix-net

  # Serviço da Interface Web do Zabbix (agora com MySQL)
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
      - ZBX_SERVER_HOST=zabbix-server
    restart: unless-stopped
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

# Define a rede para os contêineres se comunicarem
networks:
  zabbix-net:
    driver: bridge