version: '3.9'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - ./zbx_alertscripts:/usr/lib/zabbix/alertscripts
      - ./certs:/var/lib/zabbix/enc
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
      - ZBX_DBTLSCONNECT=verify_ca
      - ZBX_DB_TLSCAFILE=/var/lib/zabbix/enc/BaltimoreCyberTrustRoot.crt
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./certs:/var/lib/zabbix/enc
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_DBTLSCONNECT=verify_ca
      - ZBX_DB_TLSCAFILE=/var/lib/zabbix/enc/BaltimoreCyberTrustRoot.crt
    restart: unless-stopped
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge
