services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
      - MYSQL_DATABASE=zabbix
      # TLS
      - ZBX_DB_TLSCONNECT=verify_ca
      - ZBX_DB_TLSCAFILE=/var/lib/zabbix/enc/azure-mysql-ca-bundle.pem
      # Opcional (depois que tudo estiver OK): usar verify_full para validar hostname
      # - ZBX_DB_TLSCONNECT=verify_full
    volumes:
      - ./certs:/var/lib/zabbix/enc:ro
    # ... (restante da sua config)

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=db-zabbix-00.mysql.database.azure.com
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbixadmin
      - MYSQL_PASSWORD=Bruno@123
      - MYSQL_DATABASE=zabbix
      # TLS
      - ZBX_DB_TLSCONNECT=verify_ca
      - ZBX_DB_TLSCAFILE=/var/lib/zabbix/enc/azure-mysql-ca-bundle.pem
    volumes:
      - ./certs:/var/lib/zabbix/enc:ro
    # ... (portas, etc.)
